"""Workflow for segmenting a CT image and converting anatomy groups to VTK surfaces and meshes.

The workflow segments a 3D CT image using a chosen backend, then extracts one VTP
(surface) and one VTU (tetrahedral volume mesh, generated by netgen from that
surface) per non-empty anatomy group.  Each output object carries anatomy
metadata and solid color from :class:`USDAnatomyTools` as field and cell data
so that downstream tools (PyVista, Paraview, USD pipeline) can use them
directly.

Typical usage::

    import itk
    from physiomotion4d import (
        SegmentChestTotalSegmentatorWithContrast,
        WorkflowConvertImageToVTK,
    )

    ct = itk.imread('chest_ct.nii.gz')
    segmenter = SegmentChestTotalSegmentatorWithContrast()
    workflow = WorkflowConvertImageToVTK(segmentation_method=segmenter)
    result = workflow.run_workflow(
        ct, surface_target_reduction=0.5, mesh_target_reduction=0.7
    )

    # Combined single-file output (default)
    ContourTools.save_combined_surface(result['surfaces'], './out', prefix='patient')
    ContourTools.save_combined_mesh(result['meshes'], './out', prefix='patient')

    # Per-group split output
    ContourTools.save_surfaces(result['surfaces'], './out', prefix='patient')
    ContourTools.save_meshes(result['meshes'], './out', prefix='patient')
"""

import logging
from typing import Any, Optional

import itk
import numpy as np
import pyvista as pv

from .contour_tools import ContourTools
from .physiomotion4d_base import PhysioMotion4DBase
from .segment_anatomy_base import SegmentAnatomyBase
from .segment_chest_total_segmentator_with_contrast import (
    SegmentChestTotalSegmentatorWithContrast,
)
from .usd_anatomy_tools import USDAnatomyTools


class WorkflowConvertImageToVTK(PhysioMotion4DBase):
    """Segment a CT image and produce per-anatomy-group VTK surfaces and meshes.

    ``segmentation_method`` accepts a pre-configured
    :class:`SegmentAnatomyBase` instance (e.g. :class:`SegmentChestTotalSegmentator`,
    :class:`SegmentChestTotalSegmentatorWithContrast` for contrast-enhanced
    studies, :class:`SegmentHeartSimpleware`, or
    :class:`SegmentHeartSimplewareTrimmedBranches` for cardiac-only
    segmentation with pulmonary/great-vessel branches trimmed). Defaults to
    a new :class:`SegmentChestTotalSegmentator` when omitted.

    **Output anatomy groups**

    Determined by the active segmenter's :attr:`SegmentAnatomyBase.taxonomy`
    (see :attr:`ANATOMY_GROUPS`).  Groups that are empty after segmentation
    are silently skipped.

    **VTK object annotation**

    Each :class:`pyvista.PolyData` surface and :class:`pyvista.UnstructuredGrid` mesh
    returned by :meth:`run_workflow` carries:

    - ``field_data['AnatomyGroup']`` — anatomy group name, e.g. ``'heart'``.
    - ``field_data['SegmentationLabelNames']`` — individual structure names within the
      group (e.g. ``['left_ventricle', 'right_ventricle', …]``).
    - ``field_data['SegmentationLabelIds']`` — corresponding integer label IDs.
    - ``field_data['AnatomyColor']`` — RGB float color from :class:`USDAnatomyTools`.
    - ``cell_data['Color']`` — RGBA uint8 array (n_cells × 4) for direct VTK rendering.

    **I/O contract**

    :meth:`run_workflow` performs *no* file I/O.  Use
    :class:`ContourTools`'s static helpers
    :meth:`ContourTools.save_surfaces`, :meth:`ContourTools.save_meshes`,
    :meth:`ContourTools.save_combined_surface`, and
    :meth:`ContourTools.save_combined_mesh` — or the CLI
    ``physiomotion4d-convert-image-to-vtk`` — to write results to disk.
    """

    def __init__(
        self,
        segmentation_method: Optional[SegmentAnatomyBase] = None,
        log_level: int | str = logging.INFO,
    ) -> None:
        """Initialize the workflow.

        Args:
            segmentation_method: Segmentation backend instance. Defaults to
                a new :class:`SegmentChestTotalSegmentatorWithContrast` when None.
            log_level: Logging level.  Default: ``logging.INFO``.

        Raises:
            TypeError: If segmentation_method is neither None nor a
                SegmentAnatomyBase instance.
        """
        super().__init__(class_name=self.__class__.__name__, log_level=log_level)

        if segmentation_method is None:
            segmentation_method = SegmentChestTotalSegmentatorWithContrast(
                log_level=log_level
            )
        elif not isinstance(segmentation_method, SegmentAnatomyBase):
            raise TypeError(
                "segmentation_method must be a SegmentAnatomyBase instance or None"
            )
        self._segmenter: SegmentAnatomyBase = segmentation_method
        self._contour_tools: ContourTools = ContourTools(log_level=log_level)

        #: Anatomy group names registered by the active segmenter's taxonomy,
        #: in the order they were first added.
        self.ANATOMY_GROUPS: tuple[str, ...] = tuple(
            self._segmenter.taxonomy.group_names()
        )

        # Build anatomy-group → RGB color from USDAnatomyTools.
        # USDAnatomyTools sets up its color dicts entirely in __init__ without
        # accessing the stage, so stage=None is safe for this lookup-only use.
        _anatomy_tools = USDAnatomyTools(stage=None, log_level=log_level)
        supported_types = set(_anatomy_tools.get_anatomy_types())
        self._anatomy_color_map: dict[str, tuple[float, float, float]] = {
            group: _anatomy_tools.get_anatomy_diffuse_color(group)
            for group in self.ANATOMY_GROUPS
            if group in supported_types
        }

    # ─────────────────────────── Internal helpers ──────────────────────────

    def _get_label_info_for_group(self, group: str) -> tuple[list[str], list[int]]:
        """Return ``(label_names, label_ids)`` for *group* from the active segmenter.

        Reads the segmenter's :class:`AnatomyTaxonomy`. Returns empty lists if
        the group is not present (e.g. HeartSimpleware does not register
        lung/bone).
        """
        mask_ids = self._segmenter.taxonomy.labels_in_group(group)
        return list(mask_ids.values()), list(mask_ids.keys())

    @staticmethod
    def _annotate(
        vtk_obj: pv.DataSet,
        group: str,
        label_names: list[str],
        label_ids: list[int],
        color_rgb: tuple[float, float, float],
    ) -> None:
        """Attach anatomy metadata and solid RGBA color to a VTK object **in-place**.

        Sets:

        - ``field_data['AnatomyGroup']`` — group name.
        - ``field_data['SegmentationLabelNames']`` — individual label names.
        - ``field_data['SegmentationLabelIds']`` — integer label IDs (int32).
        - ``field_data['AnatomyColor']`` — RGB float32 color.
        - ``cell_data['Color']`` — RGBA uint8 solid color (n_cells × 4).
        """
        vtk_obj.field_data["AnatomyGroup"] = np.array([group])
        vtk_obj.field_data["SegmentationLabelNames"] = np.array(
            label_names if label_names else [group]
        )
        vtk_obj.field_data["SegmentationLabelIds"] = np.array(label_ids, dtype=np.int32)
        vtk_obj.field_data["AnatomyColor"] = np.array(color_rgb, dtype=np.float32)

        r, g, b = color_rgb
        rgba = np.array([int(r * 255), int(g * 255), int(b * 255), 255], dtype=np.uint8)
        if vtk_obj.n_cells > 0:
            vtk_obj.cell_data["Color"] = np.tile(rgba, (vtk_obj.n_cells, 1))

    def _extract_surface(self, mask_image: Any) -> Optional[pv.PolyData]:
        """Extract a smoothed triangulated surface (VTP) from a binary mask image.

        Delegates to :meth:`ContourTools.extract_contours`.

        Returns:
            Smoothed :class:`pyvista.PolyData`, or ``None`` if the mask is empty.
        """
        arr = itk.GetArrayFromImage(mask_image)
        if int(arr.sum()) == 0:
            return None
        return self._contour_tools.extract_contours(mask_image)

    def _extract_mesh(
        self, surface: pv.PolyData, mesh_target_reduction: float = 0.0
    ) -> Optional[pv.UnstructuredGrid]:
        """Generate a tetrahedral volume mesh (VTU) from a closed surface.

        Delegates to :meth:`ContourTools.extract_mesh`.

        Args:
            surface: Closed, triangulated surface for one anatomy group (as
                returned by :meth:`_extract_surface`).
            mesh_target_reduction: Fraction in ``[0, 1)`` of surface triangles
                to remove before meshing.  ``0.0`` (default) skips decimation.

        Returns:
            :class:`pyvista.UnstructuredGrid` of tetrahedral cells, or
            ``None`` if the surface is empty or no volume mesh could be
            generated from it.
        """
        return self._contour_tools.extract_mesh(surface, mesh_target_reduction)

    # ─────────────────────────── Main workflow ─────────────────────────────

    def run_workflow(
        self,
        input_image: Any,
        anatomy_groups: Optional[list[str]] = None,
        surface_target_reduction: float = 0.0,
        mesh_target_reduction: float = 0.0,
    ) -> dict[str, Any]:
        """Segment the CT image and extract per-anatomy-group VTK objects.

        Args:
            input_image: Input 3D CT image (``itk.Image``).
            anatomy_groups: Subset of anatomy groups to process.  ``None`` (default)
                processes all non-empty groups.  Valid names are given by
                :attr:`ANATOMY_GROUPS`, derived from the active segmenter's
                taxonomy.
            surface_target_reduction: Fraction in ``[0, 1)`` of surface
                triangles to remove via ``decimate_pro(surface_target_reduction,
                preserve_topology=True)``.  ``0.0`` (default) skips decimation.
            mesh_target_reduction: Fraction in ``[0, 1)`` of the surface's
                triangles to remove (via the same ``decimate_pro`` call)
                before it is handed to netgen for tetrahedral meshing.  A
                coarser input surface yields a coarser volume mesh — netgen
                itself has no post-hoc decimation.  ``0.0`` (default) skips
                decimation and meshes the surface as extracted.

        Returns:
            ``dict`` with the following keys:

            - ``'surfaces'`` — ``dict[str, pv.PolyData]``: smoothed surface per group.
            - ``'meshes'`` — ``dict[str, pv.UnstructuredGrid]``: tetrahedral volume
              mesh per group, generated by netgen from that group's surface.
            - ``'labelmap'`` — ``itk.Image``: detailed per-structure segmentation
              labelmap from the segmenter.
            - ``'segmentation_masks'`` — ``dict[str, itk.Image]``: per-group binary
              masks used to produce the VTK objects.

        Raises:
            ValueError: If any name in *anatomy_groups* is invalid.
        """
        self.log_section("STARTING IMAGE TO VTK WORKFLOW")

        # Validate requested groups
        if anatomy_groups is not None:
            invalid = [g for g in anatomy_groups if g not in self.ANATOMY_GROUPS]
            if invalid:
                raise ValueError(
                    f"Unknown anatomy groups: {invalid}. "
                    f"Valid: {list(self.ANATOMY_GROUPS)}"
                )
            groups_to_process: list[str] = list(anatomy_groups)
        else:
            groups_to_process = list(self.ANATOMY_GROUPS)

        # Run segmenter
        self.log_info("Running segmenter: %s", type(self._segmenter).__name__)

        self.log_section("Running segmentation")
        seg_result: dict[str, Any] = self._segmenter.segment(input_image)

        # Extract VTK objects per anatomy group
        self.log_section("Extracting VTK objects")
        surfaces: dict[str, pv.PolyData] = {}
        meshes: dict[str, pv.UnstructuredGrid] = {}
        seg_masks: dict[str, Any] = {}

        for group in groups_to_process:
            if group not in seg_result:
                self.log_warning(
                    "Group %s absent from segmentation result — skipping", group
                )
                continue

            mask_image = seg_result[group]
            if int(itk.GetArrayFromImage(mask_image).sum()) == 0:
                self.log_info("Group %s is empty — skipping", group)
                continue

            self.log_info("Processing anatomy group: %s", group)
            seg_masks[group] = mask_image

            label_names, label_ids = self._get_label_info_for_group(group)
            color = self._anatomy_color_map.get(group, (0.7, 0.7, 0.7))

            self.log_info("  Extracting surface for: %s", group)
            base_surface = self._extract_surface(mask_image)
            if base_surface is None:
                continue

            export_surface = base_surface
            if surface_target_reduction > 0.0:
                export_surface = export_surface.decimate_pro(
                    surface_target_reduction, preserve_topology=True
                )
            self._annotate(export_surface, group, label_names, label_ids, color)
            surfaces[group] = export_surface

            self.log_info("  Extracting volume mesh for: %s", group)
            mesh = self._extract_mesh(base_surface, mesh_target_reduction)
            if mesh is not None:
                self._annotate(mesh, group, label_names, label_ids, color)
                meshes[group] = mesh

        self.log_section("IMAGE TO VTK WORKFLOW COMPLETE")
        self.log_info("Surfaces extracted: %d", len(surfaces))
        self.log_info("Meshes extracted:   %d", len(meshes))

        return {
            "surfaces": surfaces,
            "meshes": meshes,
            "labelmap": seg_result["labelmap"],
            "segmentation_masks": seg_masks,
        }
